### ISSUE TITLE
collector has no descriptors

### ISSUE THREAD

**Issue by madic-creates** [discordianfish/pubgtracker_exporter#1]
Hello,
I've cloned the git repo, build the container with 'docker build -t "pubgtracker_exporter" .' and startet it with 'docker run -d -p 8080:8080 -i -t pubgtracker_exporter'
But I always get the following error if I want to pull metrics from it:

2018/01/12 09:48:26 http: panic serving 192.168.1.184:12582: collector has no descriptors
goroutine 68 [running]:
net/http.(*conn).serve.func1(0xc42023e460)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x6f8fa0, 0xc4202a4430)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/discordianfish/pubgtracker_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420292c00, 0xc420107c40, 0x1, 0x1)
        /go/src/github.com/discordianfish/pubgtracker_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:354 +0x9e
main.handler(0x914ac0, 0xc4202a09a0, 0xc42012f400, 0xc4200c1240)
        /go/src/github.com/discordianfish/pubgtracker_exporter/main.go:100 +0x3ee
main.main.func1(0x914ac0, 0xc4202a09a0, 0xc42012f400)
        /go/src/github.com/discordianfish/pubgtracker_exporter/main.go:180 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42000f1d0, 0x914ac0, 0xc4202a09a0, 0xc42012f400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0x94a940, 0x914ac0, 0xc4202a09a0, 0xc42012f400)
        /usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc420065520, 0x914ac0, 0xc4202a09a0, 0xc42012f400)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42023e460, 0x9151c0, 0xc420292b00)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288

I also tried another api key and with other users. Everytime the same error. Any idea?

**Comment by discordianfish** [comment]
Yes, it's broke because the pubtracker api changed and go-pubg wasn't updated: https://github.com/albshin/go-pubg/issues/6
